spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 2
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/alphalab
    username: postgres
    password: postgres